name: b_cara
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.3
  curved_navigation_bar: ^1.0.3
  emoji_picker_flutter: ^1.6.1
  enough_giphy_flutter: ^0.4.0
  permission_handler: ^10.4.3
  flutter_riverpod: ^2.3.6
  flutter_sound: ^9.2.13
  flutter_contacts: ^1.1.7+1
  country_picker: ^2.0.20
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  firebase_storage: ^11.2.5
  video_compress: ^3.1.2
  path_provider: ^2.0.15
  video_player: ^2.2.11
  audioplayers: ^4.1.0
  swipe_to: ^1.0.2
  story_view: ^0.15.0
  flutter_svg: ^2.0.5
  agora_uikit: ^1.3.6
  uuid: ^3.0.7
  image_picker: ^1.0.2
  timeago: ^3.5.0
  provider: ^6.0.5
  intl: ^0.18.1
  get: ^4.6.5
  video_thumbnail: ^0.5.3
  agora_rtc_engine: ^6.2.2
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  lottie: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
